In [23]:
import logging

import numpy as np

from yass.preprocessing import Preprocessor
from yass.mainprocess import Mainprocessor
from yass.deconvolution import Deconvolution
import yass

logging.basicConfig(level=logging.DEBUG)

In [2]:
# neural network detector
cfg = yass.Config.from_yaml('../config/nnet100k.yaml')
pp = Preprocessor(cfg)
score, clr_idx, spt = pp.process()

INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/ae_31.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/ae_31.ckpt
INFO:yass.preprocessing:Preprocessing the data in progress...


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/detectnet1.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/detectnet1.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/ae_31.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/ae_31.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/triagenet1.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/triagenet1.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/triagenet1.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/triagenet1.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/triagenet1.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/triagenet1.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/triagenet1.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/triagenet1.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/triagenet1.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/triagenet1.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/triagenet1.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/triagenet1.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/triagenet1.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/triagenet1.ckpt
N/A% (0 of 1) |                          | Elapsed Time: 0:00:00 ETA:  --:--:--INFO:yass.preprocessing:Preprocessing done in 2 seconds.
INFO:yass.preprocessing:	reading data:	0.004927 seconds
INFO:yass.preprocessing:	filtering:	0.012559 seconds
INFO:yass.preprocessing:	standardization:	0.021076 seconds
INFO:yass.preprocessing:	detection:	1.180808 seconds
INFO:yass.preprocessing:	whitening:	0.020394 seconds
INFO:yass.preprocessing:	saving recording:	0.002429 seconds
INFO:yass.preprocessing:	getting waveforms:	0.810137 seconds
100% (1 of 1) |###########################| Elapsed Time: 0:00:00 Time: 0:00:00


In [4]:
score[0].shape

(24, 3, 7)

In [6]:
score[0]

array([[[  2.12724503,   6.49735357,   0.03667137,   1.8401479 ,
           0.25868987,  -1.13400624,  -0.74167524],
        [  2.82354429,  -0.21368821,  -2.26714599,   1.31040094,
          -2.14879721,   2.92631109,   0.31378088],
        [  8.22117109,   0.40254144,   3.80736129,  -0.5874706 ,
           4.78087142,   2.23001878,  -0.52844088]],

       [[ -1.91003287,  -1.45918352,  -0.59972211,   0.55674225,
          -2.43244654,  -2.56349125,   0.84099662],
        [  6.82814127,  -0.52108445,  -0.67965963,  -0.4838843 ,
          -0.45215467,  -1.4878021 ,   0.25661365],
        [ 13.83892413,  -0.9128819 ,   0.18716055,  -1.04250323,
           3.57164416,  -1.21543633,  -1.37136553]],

       [[ -1.46336153,  -1.9771108 ,   0.4749715 ,  -0.20675808,
           0.22800426,   3.8675096 ,  -0.13081935],
        [  3.16726082,  -1.4753275 ,  -1.04326377,   0.0983479 ,
          -0.94684156,   8.77703899,   0.15354328],
        [ 13.94340688,  -2.75022451,  -3.97711366,  -2.16020

In [7]:
clr_idx[0]

array([ 15,  24,  29,  31,  39,  64, 104, 105, 110, 111, 119, 123, 144,
       158, 163, 175, 177, 182, 222, 252, 265, 290, 305, 307])

In [8]:
mp = Mainprocessor(cfg, score, clr_idx, spt)
spike_train, spt_left = mp.mainProcess()

INFO:yass.mainprocess:Triaging...
INFO:yass.mainprocess:Coresettting...
INFO:yass.mainprocess:Masking...
INFO:yass.mainprocess:Clustering...
100% (1 of 1) |###########################| Elapsed Time: 0:00:00 Time: 0:00:00
INFO:yass.mainprocess:Getting Templates...
100% (1 of 1) |###########################| Elapsed Time: 0:00:00 Time: 0:00:00
INFO:yass.mainprocess:Mainprocess done in 0 seconds.
INFO:yass.mainprocess:	triage:	0.00598 seconds
INFO:yass.mainprocess:	coreset:	0.076853 seconds
INFO:yass.mainprocess:	masking:	0.00493 seconds
INFO:yass.mainprocess:	clustering:	0.43429 seconds
INFO:yass.mainprocess:	make templates:	0.025412 seconds


In [9]:
spike_train.shape

(444, 2)

In [10]:
spike_train

array([[ 6892,     3],
       [ 8163,     3],
       [10192,     3],
       [19108,     0],
       [32395,     3],
       [35210,     0],
       [53143,     3],
       [79251,     3],
       [83767,     3],
       [93769,     3],
       [99201,     3],
       [99449,     3],
       [ 2221,     0],
       [ 3571,     1],
       [ 5118,     1],
       [ 7783,     0],
       [ 9144,     0],
       [11792,     0],
       [12680,     0],
       [14647,     1],
       [15396,     1],
       [15481,     0],
       [17318,     0],
       [19328,     1],
       [19928,     0],
       [21602,     0],
       [24229,     1],
       [24706,     1],
       [26613,     0],
       [31129,     0],
       [31625,     0],
       [32275,     0],
       [32594,     0],
       [34399,     1],
       [35941,     0],
       [36404,     1],
       [37990,     0],
       [39415,     0],
       [39710,     1],
       [40141,     1],
       [40634,     0],
       [41765,     0],
       [45940,     0],
       [470

In [11]:
spt_left[0]

array([[ 1121,     0],
       [ 1333,     0],
       [ 1704,     0],
       [ 2107,     0],
       [ 2492,     0],
       [ 2631,     0],
       [ 2716,     0],
       [ 2813,     0],
       [ 3301,     0],
       [ 3846,     0],
       [ 3910,     0],
       [ 4243,     0],
       [ 4473,     0],
       [ 4569,     0],
       [ 4712,     0],
       [ 4807,     0],
       [ 4907,     0],
       [ 5137,     0],
       [ 5458,     0],
       [ 6016,     0],
       [ 6517,     0],
       [ 6616,     0],
       [ 6629,     0],
       [ 6879,     0],
       [ 7354,     0],
       [ 7434,     0],
       [ 7627,     0],
       [ 8010,     0],
       [ 8400,     0],
       [ 8613,     0],
       [ 8674,     0],
       [ 8764,     0],
       [ 8993,     0],
       [ 9333,     0],
       [ 9585,     0],
       [ 9734,     0],
       [10020,     0],
       [10361,     0],
       [10529,     0],
       [11371,     0],
       [11533,     0],
       [11986,     0],
       [12496,     0],
       [129

In [12]:
len(spt_left)

7

In [13]:
[l.shape for l in spt_left]

[(297, 2), (1383, 2), (887, 2), (932, 2), (1142, 2), (882, 2), (811, 2)]

In [15]:
len(spike_train)

444

In [31]:
mp.templates.shape

(7, 31, 6)

In [24]:
dc = Deconvolution(cfg, np.transpose(mp.templates,[1,0,2]), spt_left)
spikeTrain_col = dc.fullMPMU()

100% (1 of 1) |###########################| Elapsed Time: 0:00:00 Time: 0:00:00


Deconvoltuion done in 0 seconds.


In [29]:
spikeTrain_col.shape

(610, 2)

In [27]:
spikeTrain = np.concatenate((spikeTrain_col, spike_train))
idx_sort = np.argsort(spikeTrain[:, 0])
spikeTrain = spikeTrain[idx_sort]
    
idx_keep = np.zeros(spikeTrain.shape[0],'bool')
for k in range(mp.templates.shape[2]):
    idx_c = np.where(spikeTrain[:,1] == k)[0]
    idx_keep[idx_c[np.concatenate(([True], np.diff(spikeTrain[idx_c,0]) > 1))]] = 1
    spikeTrain = spikeTrain[idx_keep]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 0 but corresponding boolean dimension is 1