In [28]:
import logging

import matplotlib.pyplot as plt
import numpy as np

import yass
from yass import preprocess
from yass import process
from yass import deconvolution

In [2]:
# configure logging module to get useful information
logging.basicConfig(level=logging.INFO)

# set yass configuration parameters
yass.set_config('../config/nnet100k.yaml')

# Preprocessor

In [3]:
# run preprocessor
score, clr_idx, spt = preprocess.run()

INFO:yass.batch.batch:Number of batches: 1. Batch size: 100000 (observations  per channel. Residual: 0. Total number of observations 100000
INFO:yass.preprocess.run:Initialized butterworth batch processor: BatchProcessor for file /users/Edu/data/yass/sample_100k.bin (1400000 bytes). Already processed 0 out of 1 batches. Max memory: 1000000000 bytes
INFO:yass.batch.batch:Number of batches: 1. Batch size: 100000 (observations  per channel. Residual: 0. Total number of observations 100000
INFO:yass.batch.batch:Number of batches: 1. Batch size: 100000 (observations  per channel. Residual: 0. Total number of observations 100000
INFO:yass.preprocess.run:Initialized standarization batch processor: BatchProcessor for file /users/Edu/data/yass/tmp/filtered.bin (5600000 bytes). Already processed 0 out of 1 batches. Max memory: 1000000000 bytes
INFO:yass.batch.batch:Number of batches: 1. Batch size: 100000 (observations  per channel. Residual: 0. Total number of observations 100000
INFO:yass.prep

INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/ae_31.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/ae_31.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/detectnet1.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/detectnet1.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/ae_31.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/ae_31.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/triagenet1.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/triagenet1.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/triagenet1.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/triagenet1.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/triagenet1.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/triagenet1.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/triagenet1.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/triagenet1.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/triagenet1.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/triagenet1.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/triagenet1.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/triagenet1.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/triagenet1.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/triagenet1.ckpt
INFO:yass.preprocess.run:Preprocessing done in 2 seconds.
INFO:yass.preprocess.run:	reading data:	0 seconds
INFO:yass.preprocess.run:	filtering:	0 seconds
INFO:yass.preprocess.run:	standardization:	0 seconds
INFO:yass.preprocess.run:	detection:	1.145935 seconds
INFO:yass.preprocess.run:	whitening:	1.1e-05 seconds
INFO:yass.preprocess.run:	saving recording:	0.003986 seconds
INFO:yass.preprocess.run:	getting waveforms:	0.81123 seconds


In [ ]:
len(score)

In [4]:
score[0].shape

(22, 3, 7)

In [6]:
score[0]

array([[[  3.98813212e+00,   8.32979888e+00,   9.84545873e-01,
           1.34839546e+00,   2.65142497e+00,   5.67028809e+00,
           8.91649950e-01],
        [  3.46519477e+00,   3.02116071e+00,   1.05182613e+00,
          -1.87470514e+00,   4.42119644e+00,  -5.98015241e+00,
          -1.62855242e+00],
        [  1.12311119e+01,   7.15840923e+00,   9.29220440e+00,
           2.01636504e+00,   7.67634978e+00,   2.26197873e+00,
           6.74655897e+00]],

       [[  6.49934522e-01,  -5.50504610e-02,   5.68674515e-01,
          -2.40688743e+00,  -3.74716576e+00,   1.15302746e+00,
           3.75213928e-01],
        [  4.72369800e+00,   2.74109712e+00,   3.97610253e+00,
           4.36987487e-01,  -4.22633906e-01,   9.56827002e-01,
           5.35592920e-01],
        [  8.97611452e+00,   3.80347012e+00,   3.29320793e+00,
           7.18605565e+00,   6.36367060e+00,   3.32967122e+00,
           2.59314482e+00]],

       [[  3.53008119e+00,   6.30151634e+00,   1.12843817e+00,
         

In [ ]:
len(clr_idx)

In [7]:
clr_idx[0].shape

(22,)

In [8]:
clr_idx[0]

array([  8,  11,  15,  24,  31,  50,  61, 123, 158, 159, 161, 172, 182,
       183, 214, 222, 228, 235, 251, 293, 305, 307])

In [ ]:
len(spt)

In [ ]:
spt[0].shape

In [ ]:
spt[2][:,1]

# Processor

In [9]:
# run processor
spike_train, spt_left, templates = process.run(score, clr_idx, spt)

INFO:yass.process.run:Triaging...
INFO:yass.process.run:Coresettting...
INFO:yass.process.run:Masking...
INFO:yass.process.run:Clustering...
100% (1 of 1) |###########################| Elapsed Time: 0:00:00 Time: 0:00:00
INFO:yass.process.run:Getting Templates...
100% (1 of 1) |###########################| Elapsed Time: 0:00:00 Time: 0:00:00
INFO:yass.process.run:Mainprocess done in 0 seconds.
INFO:yass.process.run:	triage:	0.006406 seconds
INFO:yass.process.run:	coreset:	0.061557 seconds
INFO:yass.process.run:	masking:	0.004421 seconds
INFO:yass.process.run:	clustering:	0.478669 seconds
INFO:yass.process.run:	make templates:	0.040645 seconds


In [10]:
spike_train.shape

(478, 2)

In [11]:
spike_train

array([[ 4153,     3],
       [ 4717,     2],
       [ 6862,     3],
       [ 8523,     2],
       [14067,     3],
       [17762,     3],
       [35813,     2],
       [47746,     1],
       [48721,     1],
       [53113,     2],
       [53488,     1],
       [64242,     2],
       [69814,     1],
       [72314,     2],
       [94937,     2],
       [99171,     3],
       [99419,     3],
       [ 1431,     4],
       [ 1856,     4],
       [ 3541,     5],
       [ 9409,     4],
       [10669,     4],
       [11321,     4],
       [11846,     5],
       [12181,     4],
       [13206,     4],
       [14617,     5],
       [15106,     4],
       [15366,     5],
       [16352,     4],
       [18346,     2],
       [19298,     5],
       [20119,     5],
       [22836,     4],
       [24676,     5],
       [26583,     4],
       [30310,     1],
       [30371,     4],
       [30762,     4],
       [31099,     4],
       [32564,     4],
       [34369,     5],
       [35911,     4],
       [377

In [12]:
len(spt_left)

7

In [ ]:
[s.shape for s in spt_left]

In [ ]:
spt_left[0]

In [14]:
templates.shape

(7, 31, 1)

In [13]:
[l.shape for l in spt_left]

[(292, 2), (1353, 2), (874, 2), (926, 2), (1163, 2), (879, 2), (806, 2)]

In [20]:
len(spike_train)

478

In [31]:
templates.shape

(7, 31, 1)

In [29]:
d = deconvolution.Deconvolution(yass.read_config(),
                                np.transpose(templates,[1,0,2]), spike_train)

In [30]:
d.fullMPMU()

IndexError: too many indices for array