In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import logging

import numpy as np

from yass.preprocessing import Preprocessor
from yass.mainprocess import Mainprocessor
from yass.deconvolution import Deconvolution
import yass

logging.basicConfig(level=logging.DEBUG)

In [3]:
# neural network detector
cfg = yass.Config.from_yaml('../config/nnet100k.yaml')
pp = Preprocessor(cfg)
score, clr_idx, spt = pp.process()

INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/ae_31.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/ae_31.ckpt
INFO:yass.preprocessing:Preprocessing the data in progress...


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/detectnet1.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/detectnet1.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/ae_31.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/ae_31.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/triagenet1.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/triagenet1.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/triagenet1.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/triagenet1.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/triagenet1.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/triagenet1.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/triagenet1.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/triagenet1.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/triagenet1.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/triagenet1.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/triagenet1.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/triagenet1.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/triagenet1.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/triagenet1.ckpt
N/A% (0 of 1) |                          | Elapsed Time: 0:00:00 ETA:  --:--:--INFO:yass.preprocessing:Preprocessing done in 2 seconds.
INFO:yass.preprocessing:	reading data:	0.004105 seconds
INFO:yass.preprocessing:	filtering:	0.011824 seconds
INFO:yass.preprocessing:	standardization:	0.022557 seconds
INFO:yass.preprocessing:	detection:	1.151383 seconds
INFO:yass.preprocessing:	whitening:	0.018038 seconds
INFO:yass.preprocessing:	saving recording:	0.002096 seconds
INFO:yass.preprocessing:	getting waveforms:	0.74196 seconds
100% (1 of 1) |###########################| Elapsed Time: 0:00:00 Time: 0:00:00


In [4]:
score[0].shape

(24, 3, 7)

In [5]:
score[0][:10]

array([[[  2.12724503,   6.49735357,   0.03667137,   1.8401479 ,
           0.25868987,  -1.13400624,  -0.74167524],
        [  2.82354429,  -0.21368821,  -2.26714599,   1.31040094,
          -2.14879721,   2.92631109,   0.31378088],
        [  8.22117109,   0.40254144,   3.80736129,  -0.5874706 ,
           4.78087142,   2.23001878,  -0.52844088]],

       [[ -1.91003287,  -1.45918352,  -0.59972211,   0.55674225,
          -2.43244654,  -2.56349125,   0.84099662],
        [  6.82814127,  -0.52108445,  -0.67965963,  -0.4838843 ,
          -0.45215467,  -1.4878021 ,   0.25661365],
        [ 13.83892413,  -0.9128819 ,   0.18716055,  -1.04250323,
           3.57164416,  -1.21543633,  -1.37136553]],

       [[ -1.46336153,  -1.9771108 ,   0.4749715 ,  -0.20675808,
           0.22800426,   3.8675096 ,  -0.13081935],
        [  3.16726082,  -1.4753275 ,  -1.04326377,   0.0983479 ,
          -0.94684156,   8.77703899,   0.15354328],
        [ 13.94340688,  -2.75022451,  -3.97711366,  -2.16020

In [6]:
clr_idx[0]

array([ 15,  24,  29,  31,  39,  64, 104, 105, 110, 111, 119, 123, 144,
       158, 163, 175, 177, 182, 222, 252, 265, 290, 305, 307])

In [7]:
[s.shape for s in score]

[(24, 3, 7),
 (72, 3, 4),
 (14, 3, 4),
 (18, 3, 4),
 (140, 3, 4),
 (111, 3, 4),
 (165, 3, 4)]

In [8]:
[s.shape for s in clr_idx]

[(24,), (72,), (14,), (18,), (140,), (111,), (165,)]

In [9]:
[s.shape for s in spt]

[(309, 2), (1446, 2), (894, 2), (945, 2), (1259, 2), (975, 2), (950, 2)]

In [10]:
mp = Mainprocessor(cfg, score, clr_idx, spt)
spike_train, spt_left = mp.mainProcess()

INFO:yass.mainprocess:Triaging...
INFO:yass.mainprocess:Coresettting...
INFO:yass.mainprocess:Masking...
INFO:yass.mainprocess:Clustering...
100% (1 of 1) |###########################| Elapsed Time: 0:00:00 Time: 0:00:00
INFO:yass.mainprocess:Getting Templates...
100% (1 of 1) |###########################| Elapsed Time: 0:00:00 Time: 0:00:00
INFO:yass.mainprocess:Mainprocess done in 0 seconds.
INFO:yass.mainprocess:	triage:	0.006152 seconds
INFO:yass.mainprocess:	coreset:	0.080327 seconds
INFO:yass.mainprocess:	masking:	0.005249 seconds
INFO:yass.mainprocess:	clustering:	0.385789 seconds
INFO:yass.mainprocess:	make templates:	0.022472 seconds


In [26]:
spike_train.shape

(450, 2)

In [12]:
spike_train

array([[ 4747,     3],
       [ 6892,     3],
       [ 8163,     3],
       [10192,     3],
       [19108,     3],
       [30338,     3],
       [32395,     3],
       [35210,     3],
       [49457,     3],
       [51978,     3],
       [53143,     3],
       [79251,     3],
       [83767,     3],
       [93769,     3],
       [99201,     3],
       [99449,     3],
       [ 2221,     3],
       [ 3571,     3],
       [ 5118,     3],
       [ 7783,     3],
       [ 9144,     3],
       [11792,     3],
       [12680,     3],
       [14647,     3],
       [15396,     3],
       [15481,     3],
       [17318,     3],
       [19328,     3],
       [19928,     3],
       [21602,     3],
       [23432,     3],
       [24229,     3],
       [24706,     3],
       [26613,     3],
       [31129,     3],
       [31625,     3],
       [32275,     3],
       [32594,     3],
       [34399,     3],
       [35941,     3],
       [36404,     3],
       [37990,     3],
       [39415,     3],
       [397

In [13]:
spt_left[0]

array([[ 1121,     0],
       [ 1333,     0],
       [ 1704,     0],
       [ 2107,     0],
       [ 2492,     0],
       [ 2631,     0],
       [ 2716,     0],
       [ 2813,     0],
       [ 3301,     0],
       [ 3846,     0],
       [ 3910,     0],
       [ 4243,     0],
       [ 4473,     0],
       [ 4569,     0],
       [ 4712,     0],
       [ 4907,     0],
       [ 5137,     0],
       [ 5458,     0],
       [ 6016,     0],
       [ 6517,     0],
       [ 6616,     0],
       [ 6629,     0],
       [ 6879,     0],
       [ 7354,     0],
       [ 7434,     0],
       [ 7627,     0],
       [ 8010,     0],
       [ 8400,     0],
       [ 8613,     0],
       [ 8674,     0],
       [ 8764,     0],
       [ 8993,     0],
       [ 9333,     0],
       [ 9585,     0],
       [ 9734,     0],
       [10020,     0],
       [10361,     0],
       [10529,     0],
       [11371,     0],
       [11533,     0],
       [11986,     0],
       [12496,     0],
       [12955,     0],
       [132

In [14]:
len(spt_left)

7

In [15]:
[l.shape for l in spt_left]

[(293, 2), (1381, 2), (887, 2), (931, 2), (1142, 2), (884, 2), (810, 2)]

In [16]:
len(spike_train)

450

In [17]:
mp.templates.shape

(7, 31, 5)

In [18]:
mp.templates

array([[[  1.89062493e-01,   3.46746030e-01,   5.29473687e-01,
          -5.07199995e-01,  -1.91896551e-01],
        [  1.29999997e-01,   4.81825393e-01,   6.71315787e-01,
          -9.15600004e-01,  -4.85086203e-01],
        [  2.62499994e-02,   5.58174600e-01,   6.63684213e-01,
          -1.26050001e+00,  -8.53965516e-01],
        ..., 
        [ -5.54687501e-01,   2.96825397e-01,   3.53421051e-01,
          -8.36300002e-01,  -2.60862074e-01],
        [ -4.75000004e-01,   2.86031748e-01,   3.11052630e-01,
          -7.96999999e-01,  -1.20862068e-01],
        [ -3.59999997e-01,   2.71587298e-01,   2.61578948e-01,
          -7.39100000e-01,   3.52586198e-02]],

       [[  1.35000001e-01,   2.43412694e-01,   1.05394735e-01,
          -4.22100004e-01,   4.28706895e-01],
        [  2.00937503e-01,   4.50396825e-01,   1.42105265e-01,
          -9.42400005e-01,   6.94827586e-01],
        [  1.95625000e-01,   6.34047619e-01,   1.93815792e-01,
          -1.46810001e+00,   6.30775861e-01],
   

In [19]:
mp.templates.shape

(7, 31, 5)

In [20]:
np.transpose(mp.templates,[1,0,2]).shape

(31, 7, 5)

In [28]:
[s.shape for s in spt_left]

[(293, 2), (1381, 2), (887, 2), (931, 2), (1142, 2), (884, 2), (810, 2)]

In [21]:
dc = Deconvolution(cfg, np.transpose(mp.templates,[1,0,2]), spt_left)
spikeTrain_col = dc.fullMPMU()

100% (1 of 1) |###########################| Elapsed Time: 0:00:00 Time: 0:00:00


(293, 2)
(1381, 2)
(887, 2)
(931, 2)
(1142, 2)
(884, 2)
(810, 2)
Deconvoltuion done in 0 seconds.


In [22]:
spikeTrain_col.shape

(569, 2)

In [30]:
spikeTrain_col.shape

(569, 2)

In [29]:
spikeTrain_col

array([[ 1273,     3],
       [ 2046,     3],
       [ 2571,     3],
       ..., 
       [55284,     0],
       [71682,     0],
       [71733,     4]])

In [23]:
spikeTrain = np.concatenate((spikeTrain_col, spike_train))
idx_sort = np.argsort(spikeTrain[:, 0])
spikeTrain = spikeTrain[idx_sort]
    
idx_keep = np.zeros(spikeTrain.shape[0],'bool')
for k in range(mp.templates.shape[2]):
    idx_c = np.where(spikeTrain[:,1] == k)[0]
    idx_keep[idx_c[np.concatenate(([True], np.diff(spikeTrain[idx_c,0]) > 1))]] = 1
    spikeTrain = spikeTrain[idx_keep]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 0 but corresponding boolean dimension is 1