In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import logging

import matplotlib.pyplot as plt
import numpy as np

import yass
from yass import preprocess
from yass import process
from yass import deconvolution

In [3]:
# configure logging module to get useful information
logging.basicConfig(level=logging.INFO)

# set yass configuration parameters
yass.set_config('../config/nnet100k.yaml')

# Preprocessor

In [4]:
# run preprocessor
score, clr_idx, spt = preprocess.run()

INFO:yass.batch.batch:Number of batches: 1. Batch size: 100000 (observations  per channel. Residual: 0. Total number of observations 100000
INFO:yass.preprocess.run:Initialized butterworth batch processor: BatchProcessor for file /users/Edu/data/yass/sample_100k.bin (1400000 bytes). Already processed 0 out of 1 batches. Max memory: 1000000000 bytes
INFO:yass.batch.batch:Number of batches: 1. Batch size: 100000 (observations  per channel. Residual: 0. Total number of observations 100000
INFO:yass.batch.batch:Number of batches: 1. Batch size: 100000 (observations  per channel. Residual: 0. Total number of observations 100000
INFO:yass.preprocess.run:Initialized standarization batch processor: BatchProcessor for file /users/Edu/data/yass/tmp/filtered.bin (5600000 bytes). Already processed 0 out of 1 batches. Max memory: 1000000000 bytes
INFO:yass.batch.batch:Number of batches: 1. Batch size: 100000 (observations  per channel. Residual: 0. Total number of observations 100000
INFO:yass.prep

INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/ae_31.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/ae_31.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/detectnet1.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/detectnet1.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/ae_31.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/ae_31.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/triagenet1.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/triagenet1.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/triagenet1.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/triagenet1.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/triagenet1.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/triagenet1.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/triagenet1.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/triagenet1.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/triagenet1.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/triagenet1.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/triagenet1.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/triagenet1.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/triagenet1.ckpt


INFO:tensorflow:Restoring parameters from /users/Edu/data/yass/triagenet1.ckpt
INFO:yass.preprocess.run:Preprocessing done in 2 seconds.
INFO:yass.preprocess.run:	reading data:	0 seconds
INFO:yass.preprocess.run:	filtering:	0 seconds
INFO:yass.preprocess.run:	standardization:	0 seconds
INFO:yass.preprocess.run:	detection:	1.169756 seconds
INFO:yass.preprocess.run:	whitening:	0.018186 seconds
INFO:yass.preprocess.run:	saving recording:	0.002257 seconds
INFO:yass.preprocess.run:	getting waveforms:	0.802654 seconds


In [5]:
len(score)

7

In [6]:
score[0].shape

(24, 3, 7)

In [7]:
score[0][:10]

array([[[  2.12516378,   6.49560078,   0.03912137,   1.84174519,
           0.26052048,  -1.13213871,  -0.73797652],
        [  2.8225692 ,  -0.21323244,  -2.26516002,   1.30797597,
          -2.1469118 ,   2.92537192,   0.31439169],
        [  8.21978387,   0.40392378,   3.80732387,  -0.58009342,
           4.77968914,   2.2307871 ,  -0.52612647]],

       [[ -1.90976469,  -1.4590097 ,  -0.60051599,   0.55297806,
          -2.43148874,  -2.56307796,   0.83960869],
        [  6.82840736,  -0.52139048,  -0.67981387,  -0.48588003,
          -0.45237832,  -1.48731292,   0.25520471],
        [ 13.83891079,  -0.91271949,   0.18715997,  -1.04290219,
           3.56932953,  -1.2146041 ,  -1.37132214]],

       [[ -1.46332119,  -1.97585361,   0.47494556,  -0.20519677,
           0.22794376,   3.86599967,  -0.13060029],
        [  3.16656985,  -1.47383773,  -1.04128221,   0.10063019,
          -0.94562682,   8.77413999,   0.15417064],
        [ 13.94479422,  -2.75082615,  -3.97680213,  -2.16350

In [8]:
len(clr_idx)

7

In [9]:
clr_idx[0].shape

(24,)

In [10]:
clr_idx[0]

array([ 15,  24,  29,  31,  39,  64, 104, 105, 110, 111, 119, 123, 144,
       158, 163, 175, 177, 182, 222, 252, 265, 290, 305, 307])

In [11]:
len(spt)

7

In [12]:
spt[0].shape

(309, 2)

In [13]:
spt[2][:,1]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0,

In [14]:
[s.shape for s in score]

[(24, 3, 7),
 (72, 3, 4),
 (14, 3, 4),
 (19, 3, 4),
 (140, 3, 4),
 (110, 3, 4),
 (164, 3, 4)]

In [15]:
[s.shape for s in clr_idx]

[(24,), (72,), (14,), (19,), (140,), (110,), (164,)]

In [16]:
[s.shape for s in spt]

[(309, 2), (1445, 2), (892, 2), (943, 2), (1258, 2), (974, 2), (950, 2)]

# Processor

In [31]:
# run processor
spike_train, spt_left, templates = process.run(score, clr_idx, spt)

INFO:yass.process.run:Triaging...
INFO:yass.process.run:Coresettting...
INFO:yass.process.run:Masking...
INFO:yass.process.run:Clustering...
100% (1 of 1) |###########################| Elapsed Time: 0:00:00 Time: 0:00:00
INFO:yass.process.run:Getting Templates...
100% (1 of 1) |###########################| Elapsed Time: 0:00:00 Time: 0:00:00
INFO:yass.process.run:Mainprocess done in 0 seconds.
INFO:yass.process.run:	triage:	0.004989 seconds
INFO:yass.process.run:	coreset:	0.079783 seconds
INFO:yass.process.run:	masking:	0.005222 seconds
INFO:yass.process.run:	clustering:	0.430745 seconds
INFO:yass.process.run:	make templates:	0.039326 seconds


In [32]:
spike_train.shape

(437, 2)

In [33]:
spike_train

array([[ 4717,     2],
       [ 6862,     2],
       [10162,     2],
       [19078,     2],
       [30308,     2],
       [32365,     2],
       [35180,     2],
       [49427,     2],
       [51948,     2],
       [53113,     2],
       [79221,     2],
       [83737,     2],
       [93739,     2],
       [99171,     2],
       [99419,     2],
       [ 2191,     2],
       [ 3541,     2],
       [ 5088,     2],
       [ 7753,     2],
       [ 9114,     2],
       [11762,     2],
       [12650,     2],
       [14617,     2],
       [15366,     2],
       [15451,     2],
       [17288,     2],
       [19298,     2],
       [19898,     2],
       [21572,     2],
       [23402,     2],
       [24199,     2],
       [24676,     2],
       [26583,     2],
       [31099,     2],
       [31595,     2],
       [32245,     2],
       [32564,     2],
       [34369,     2],
       [35911,     2],
       [36374,     2],
       [37960,     2],
       [39385,     2],
       [39680,     2],
       [401

In [34]:
len(spt_left)

7

In [35]:
[s.shape for s in spt_left]

[(294, 2), (1383, 2), (885, 2), (929, 2), (1144, 2), (884, 2), (815, 2)]

In [36]:
spt_left[0]

array([[ 1091,     0],
       [ 1303,     0],
       [ 1674,     0],
       [ 2077,     0],
       [ 2462,     0],
       [ 2601,     0],
       [ 2686,     0],
       [ 2783,     0],
       [ 3271,     0],
       [ 3816,     0],
       [ 3880,     0],
       [ 4213,     0],
       [ 4443,     0],
       [ 4539,     0],
       [ 4682,     0],
       [ 4877,     0],
       [ 5107,     0],
       [ 5428,     0],
       [ 5986,     0],
       [ 6487,     0],
       [ 6586,     0],
       [ 6599,     0],
       [ 6849,     0],
       [ 7324,     0],
       [ 7404,     0],
       [ 7597,     0],
       [ 7980,     0],
       [ 8193,     0],
       [ 8370,     0],
       [ 8583,     0],
       [ 8644,     0],
       [ 8734,     0],
       [ 8963,     0],
       [ 9303,     0],
       [ 9555,     0],
       [ 9704,     0],
       [ 9990,     0],
       [10331,     0],
       [10499,     0],
       [11341,     0],
       [11503,     0],
       [11956,     0],
       [12466,     0],
       [129

In [37]:
templates.shape

(7, 31, 7)

In [38]:
[l.shape for l in spt_left]

[(294, 2), (1383, 2), (885, 2), (929, 2), (1144, 2), (884, 2), (815, 2)]

In [39]:
len(spike_train)

437

In [40]:
templates.shape

(7, 31, 7)

In [41]:
[t.shape for t in templates]

[(31, 7), (31, 7), (31, 7), (31, 7), (31, 7), (31, 7), (31, 7)]

In [52]:
spike_train.shape

(437, 2)

In [53]:
d = deconvolution.Deconvolution(yass.read_config(),
                                np.transpose(templates,[1,0,2]), spt_left)

In [55]:
spike_times_col = d.fullMPMU()

100% (1 of 1) |###########################| Elapsed Time: 0:00:00 Time: 0:00:00


Deconvoltuion done in 0 seconds.


In [57]:
spike_times_col.shape

(11, 2)

In [56]:
spike_times_col

array([[ 2939,     6],
       [ 6479,     2],
       [ 8059,     3],
       [12290,     2],
       [38446,     6],
       [47654,     0],
       [69953,     6],
       [80638,     0],
       [97448,     6],
       [47654,     3],
       [80638,     3]])