In [4]:
import os.path as path
import numpy as np

In [18]:
OLD = '/ssd/data/eduardo/tmp-old-threshold'
NEW = '/ssd/data/eduardo/tmp-new-threshold'

In [21]:
clear_old = np.load(path.join(OLD, 'spike_index_clear.npy'))
clear_new = np.load(path.join(NEW, 'spike_index_clear.npy'))

In [22]:
clear_old.shape, clear_new.shape

((101861, 2), (149832, 2))

In [23]:
clear_old

array([[   2035,       0],
       [   5411,       0],
       [   6075,       0],
       ..., 
       [5998375,      48],
       [5998439,      48],
       [6000006,      48]], dtype=int32)

In [24]:
clear_new

array([[    836,       0],
       [   1046,       0],
       [   1262,       0],
       ..., 
       [5998375,      48],
       [5998439,      48],
       [5998761,      48]], dtype=int32)

In [ ]:
col_old = np.load(path.join(OLD, 'spike_index_collision.npy'))
col_new = np.load(path.join(NEW, 'spike_index_collision.npy'))

In [15]:
col_old.shape, col_new.shape

((354770, 2), (596768, 2))

In [16]:
col_old

array([[     11,       3],
       [     11,      20],
       [     11,      25],
       ..., 
       [6000017,      45],
       [6000017,      46],
       [6000017,      48]], dtype=int32)

In [17]:
col_new

array([[     22,      18],
       [     28,      46],
       [     57,      43],
       ..., 
       [5999925,      37],
       [5999945,      19],
       [5999945,      43]])